version: "3"
services:
    test_lambda:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ../tests/:/usr/src/tests
            - ../genetic_algo:/usr/src/genetic_algo
        network_mode: bridge
        entrypoint: ./entrypoint.sh
